In [ ]:
#https://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca
#https://stackoverflow.com/questions/60508233/python-implement-a-pca-using-svd

In [8]:
import numpy as np
from sklearn.decomposition import PCA

n, p = 10, 5
X = np.random.rand(n, p)

In [17]:
PCA(3).fit_transform(X)

array([[-0.03704442, -0.46279545,  0.05858614],
       [-0.43131416,  0.46907701, -0.0213612 ],
       [-0.1798541 ,  0.27704248,  0.39242182],
       [-0.54734843, -0.06195953, -0.22679276],
       [ 0.01368038, -0.39559001, -0.10240814],
       [-0.31569235, -0.22317742,  0.13213957],
       [ 0.26879694,  0.33700923, -0.26011648],
       [ 0.56849377,  0.1939513 ,  0.06333797],
       [ 0.21897836,  0.02636622, -0.14496916],
       [ 0.441304  , -0.15992382,  0.10916224]])

In [19]:
X -= np.mean(X, axis=0)


In [20]:
# the p x p covariance matrix
C = np.cov(X, rowvar=False)
print("C = \n", C)
# C is a symmetric matrix and so it can be diagonalized:
l, principal_axes = np.linalg.eig(C)  #eigenvalues, eigenvectors
# sort results wrt. eigenvalues
idx = l.argsort()[::-1]
l, principal_axes = l[idx], principal_axes[:, idx]
# the eigenvalues in decreasing order
print("l = \n", l)
# a matrix of eigenvectors (each column is an eigenvector)
print("V = \n", principal_axes)
# projections of X on the principal axes are called principal components
principal_components = X.dot(principal_axes)
print("Y = \n", principal_components)

C = 
 [[ 0.03738971  0.01426546 -0.02636341 -0.02936637 -0.03230849]
 [ 0.01426546  0.06456258 -0.00015999  0.03451973 -0.0191789 ]
 [-0.02636341 -0.00015999  0.04928801  0.03443106  0.01875109]
 [-0.02936637  0.03451973  0.03443106  0.06978757  0.01944976]
 [-0.03230849 -0.0191789   0.01875109  0.01944976  0.07593203]]
l = 
 [0.13970317 0.09984079 0.03798572 0.01579778 0.00363244]
V = 
 [[ 0.43883028  0.17827377 -0.19813109 -0.50866331 -0.69112383]
 [-0.04823955  0.7521665  -0.39759968 -0.24869917  0.46041472]
 [-0.45431677  0.04075568  0.59273308 -0.66258613  0.03977886]
 [-0.57569315  0.44504757  0.01761617  0.40463489 -0.55359763]
 [-0.51698608 -0.45026177 -0.67157704 -0.27687646 -0.04809821]]
Y = 
 [[ 0.03704442  0.46279545  0.05858614  0.02819352 -0.07027853]
 [ 0.43131416 -0.46907701 -0.0213612  -0.01085747  0.02747701]
 [ 0.1798541  -0.27704248  0.39242182 -0.10706633 -0.0588637 ]
 [ 0.54734843  0.06195953 -0.22679276 -0.02836164  0.03281464]
 [-0.01368038  0.39559001 -0.102408

In [45]:
#https://davidvandebunte.gitlab.io/executable-notes/notes/se/relationship-between-svd-and-pca.html
U, S, VT = np.linalg.svd(X, full_matrices=False)
V = VT.T # V - matrix of eigenvectors, columns of V are principal directions/axes.

#X * V = U * S * Vt * V = U * S
k=3
U=U[:,:k]
S = np.diag(S)
S=S[:k,:k]

print(U)
print()
print(S)
print()
PC = U.dot(S) 
PC_2 = X.dot(V[:,:k])
print(PC)
print(f"US == XV {np.allclose(PC,PC_2)}")


[[-0.03303683  0.48821803  0.10019901]
 [-0.38465318 -0.49484465 -0.03653374]
 [-0.1603969  -0.29226115  0.67115325]
 [-0.48813449  0.06536313 -0.38788031]
 [ 0.01220039  0.41732081 -0.17514713]
 [-0.28153972  0.23543715  0.22599636]
 [ 0.23971761 -0.35552204 -0.44487338]
 [ 0.50699226 -0.20460556  0.10832599]
 [ 0.19528857 -0.02781459 -0.24793862]
 [ 0.3935623   0.16870886  0.18669856]]

[[1.1213066  0.         0.        ]
 [0.         0.94792781 0.        ]
 [0.         0.         0.58469778]]

[[-0.03704442  0.46279545  0.05858614]
 [-0.43131416 -0.46907701 -0.0213612 ]
 [-0.1798541  -0.27704248  0.39242182]
 [-0.54734843  0.06195953 -0.22679276]
 [ 0.01368038  0.39559001 -0.10240814]
 [-0.31569235  0.22317742  0.13213957]
 [ 0.26879694 -0.33700923 -0.26011648]
 [ 0.56849377 -0.1939513   0.06333797]
 [ 0.21897836 -0.02636622 -0.14496916]
 [ 0.441304    0.15992382  0.10916224]]
US == XV True
